/* Machine-auditable migration manifest generated from dog-adm-seas seas closure. */
export const resSourceViewFiles = [
  'ditch/Modal.vue',
  'ditch/data.tsx',
  'ditch/index.vue',
  'ditch/source.vue',
  'ditch/team.vue',
  'ditch/user.vue',
  'global/consume/data.tsx',
  'global/consume/index.vue',
  'global/fb_event/data.tsx',
  'global/fb_event/index.vue',
  'global/fire/data.tsx',
  'global/fire/index.vue',
  'global/link/ChooseInput.vue',
  'global/link/CommonModal.vue',
  'global/link/DramaModal.vue',
  'global/link/Modal.vue',
  'global/link/PayModal.vue',
  'global/link/PayNewModal.vue',
  'global/link/PayNewMultiModal.vue',
  'global/link/TableModal.vue',
  'global/link/data.tsx',
  'global/link/index.vue',
  'global/link_change/data.tsx',
  'global/link_change/index.vue',
  'global/order/data.tsx',
  'global/order/index.vue',
  'global/page_manage/Modal.vue',
  'global/page_manage/data.tsx',
  'global/page_manage/index.vue',
  'global/page_manage/index_vxe_form.vue',
  'global/page_module_manage/LanguageModal.vue',
  'global/page_module_manage/Modal.vue',
  'global/page_module_manage/SourceDrawer.vue',
  'global/page_module_manage/SourceSelectModal.vue',
  'global/page_module_manage/TranslateModal.vue',
  'global/page_module_manage/data.tsx',
  'global/page_module_manage/index.vue',
  'global/read/data.tsx',
  'global/read/index.vue',
  'global/read_detail/data.tsx',
  'global/read_detail/index.vue',
  'global/return_config/Modal.vue',
  'global/return_config/data.tsx',
  'global/return_config/index.vue',
  'global/source_manage/AnchroModal.vue',
  'global/source_manage/CategorySelectModal.vue',
  'global/source_manage/ChapterModalPlayer.vue',
  'global/source_manage/ChapterModalVueVideoPlayer.vue',
  'global/source_manage/Modal.vue',
  'global/source_manage/NovalModal.vue',
  'global/source_manage/PlayModal.vue',
  'global/source_manage/PriceModal.vue',
  'global/source_manage/TagsModal.vue',
  'global/source_manage/coin-order-list.vue',
  'global/source_manage/coin-set-history.vue',
  'global/source_manage/component/PriceRangTable.vue',
  'global/source_manage/component/video.vue',
  'global/source_manage/data.tsx',
  'global/source_manage/drama-set-modal.vue',
  'global/source_manage/index.vue',
  'global/tmplate_lib/Modal.vue',
  'global/tmplate_lib/ModalItem.vue',
  'global/tmplate_lib/ModalItemDetail.vue',
  'global/tmplate_lib/ModalMoneyItem.vue',
  'global/tmplate_lib/ModalVipItem.vue',
  'global/tmplate_lib/ModalVipItemDetail.vue',
  'global/tmplate_lib/TmpReviewModal.vue',
  'global/tmplate_lib/data.tsx',
  'global/tmplate_lib/index.vue',
  'global/translate/Modal.vue',
  'global/translate/data.tsx',
  'global/translate/index.vue',
  'global/user/Modal.vue',
  'global/user/data.tsx',
  'global/user/index.vue',
  'global/user/modal_data.tsx',
  'global/user_detail/data.tsx',
  'global/user_detail/index.vue',
  'global/watch/data.tsx',
  'global/watch/index.vue',
  'log/access/data.tsx',
  'log/access/index.vue',
  'log/back/data.tsx',
  'log/back/index.vue',
  'log/error/data.tsx',
  'log/error/index.vue',
  'log/fb-follow/data.tsx',
  'log/fb-follow/index.vue',
  'log/op/data.tsx',
  'log/op/index.vue',
  'log/w2a/data.tsx',
  'log/w2a/index.vue',
  'report/ad/data.tsx',
  'report/ad/district.vue',
  'report/ad/index.vue',
  'report/ad/link.vue',
  'report/ad/plan.vue',
  'report/ad/platform.vue',
  'report/ad/position.vue',
  'report/ad/user.vue',
  'report/day/data.tsx',
  'report/day/index.vue',
  'report/day_reader/data.tsx',
  'report/day_reader/index.vue',
  'report/fb_back/data.tsx',
  'report/fb_back/index.vue',
  'report/fb_sub/data.tsx',
  'report/fb_sub/index.vue',
  'report/iap/index.vue',
  'report/iap/plan/data.tsx',
  'report/iap/plan/index.vue',
  'report/iap/plan_paytime/data.tsx',
  'report/iap/plan_paytime/index.vue',
  'report/iap/roi/Modal.vue',
  'report/iap/roi/data.tsx',
  'report/iap/roi/index.vue',
  'report/iap/total/Modal.vue',
  'report/iap/total/data.tsx',
  'report/iap/total/index.vue',
  'report/link/data.tsx',
  'report/link/index.vue',
  'report/user_income/data.tsx',
  'report/user_income/index.vue',
  'run/push/Modal.vue',
  'run/push/data.tsx',
  'run/push/index.vue',
  'run/push/record.vue',
  'set/ad/Modal.vue',
  'set/ad/data.tsx',
  'set/ad/index.vue',
  'set/category/LanguageModal.vue',
  'set/category/Modal.vue',
  'set/category/SourceSelectModal.vue',
  'set/category/data.tsx',
  'set/category/index.vue',
  'set/def_tmplate_lib/data.tsx',
  'set/def_tmplate_lib/index.vue',
  'set/ditch/Modal.vue',
  'set/ditch/data.tsx',
  'set/ditch/index.vue',
  'set/ditch/source.vue',
  'set/fb/Modal.vue',
  'set/fb/data.tsx',
  'set/fb/index.vue',
  'set/feedback/DeviceInfoModal.vue',
  'set/feedback/Modal.vue',
  'set/feedback/data.tsx',
  'set/feedback/index.vue',
  'set/follow/Modal.vue',
  'set/follow/SourceSelectModal.vue',
  'set/follow/data.tsx',
  'set/follow/index.vue',
  'set/sku/android/Modal.vue',
  'set/sku/android/data.tsx',
  'set/sku/android/index.vue',
  'set/sku/ios/Modal.vue',
  'set/sku/ios/data.tsx',
  'set/sku/ios/index.vue',
  'set/task/EditModal.vue',
  'set/task/Modal.vue',
  'set/task/SignModal.vue',
  'set/task/data.tsx',
  'set/task/index.vue',
] as const;

export const resSourceApiFiles = [
  'dashboard/index.ts',
  'ditch/index.ts',
  'global/i18n.ts',
  'global/link.ts',
  'global/order.ts',
  'global/page_manage.ts',
  'global/page_module_manage.ts',
  'global/return_config.ts',
  'global/source_manage.ts',
  'global/tmplate_lib.ts',
  'global/user.ts',
  'log/access.ts',
  'log/back.ts',
  'log/error.ts',
  'log/fb-follow.ts',
  'log/op.ts',
  'log/w2a.ts',
  'report/ad.ts',
  'report/day.ts',
  'report/day_reader.ts',
  'report/fb_back.ts',
  'report/fb_sub.ts',
  'report/iap/plan.ts',
  'report/iap/plan_paytime.ts',
  'report/iap/roi.ts',
  'report/iap/total.ts',
  'report/link.ts',
  'report/user_income.ts',
  'run/push.ts',
  'set/ad.ts',
  'set/category.ts',
  'set/fb.ts',
  'set/feedback.ts',
  'set/follow.ts',
  'set/sku/android.ts',
  'set/sku/ios.ts',
  'set/task.ts',
] as const;

export const resSourceDomains = [
  'ditch',
  'global',
  'log',
  'report',
  'run',
  'set',
] as const;

export const resRouteComponents = resSourceViewFiles
  .filter((file) => file.endsWith('.vue'))
  .map((file) => `/res/seas/${file.slice(0, -4)}`);
export const resMigrationStats = {
  apiFiles: resSourceApiFiles.length,
  domains: resSourceDomains.length,
  legacySchemaFiles: resSourceViewFiles.filter((file) =>
    file.endsWith('data.tsx'),
  ).length,
  routeComponents: resRouteComponents.length,
  viewFiles: resSourceViewFiles.length,
} as const;

/**
 * 文件闭包只能证明入口存在，不能证明旧页面的字段、交互和业务规则等价。
 * 这些计数由单元测试扫描实际源码校验，归零前不得宣称前端完整迁移。
 */
export const resMigrationAudit = {
  behaviorParity: 'partial',
  genericModalAdapters: 36,
  genericPageAdapters: 18,
  knownGaps: [
    '旧 data.tsx 的列、筛选、字典 formatter 和表单 schema 尚未逐页建立等价断言',
    '通用 ResRecordModal 只提供基础编辑、选择和播放能力，不能代表原业务弹窗等价',
    '真实后端联调、支付模板视觉预览和第三方 provider 流程仍需浏览器验收',
  ],
  sourceClosure: 'complete',
} as const;
